name: Opensource

on:
  push:
    branches: [ "teamcode-rr0.5.6" ]
  workflow_dispatch:

permissions:
    contents: write # for git push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git user config
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"

      - name: Check Env
        run: |
          pwd
          ls
          cd ..
          ls

      - name: Checkout branch
        run: |
          git checkout teamcode-opensource-rr0.5.6
          git merge teamcode-rr0.5.6 -m "Merge teamcode-rr0.5.6 into teamcode-opensource-rr0.5.6"

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      # Runs a single command using the runners shell
      - name: Run script
        env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     PATH: $PATH:/home/runner/.local/bin
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git filter-repo --path into-the-deep-modded.pdf --invert-paths --force
            git commit --allow-empty -m "自动更新"
            git push
          fi
   #       git push --force --set-upstream origin teamcode-opensource-rr0.5.6
